name: TaskTracker Frontend Pipeline

on:
  push:
    branches: [main]
    paths:
      - 'client/**'

jobs:
  build_and_deploy_frontend:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install frontend dependencies
        run: npm install
        working-directory: client

      - name: Run frontend lint
        run: npm run lint
        working-directory: client

      # Uncomment this later when tests are added
      # - name: Run frontend tests
      #   run: npm test
      #   working-directory: client

      - name: Build frontend
        run: npm run build
        working-directory: client

      - name: Deploy frontend to Vercel
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel-args: '--prod' # THIS makes sure it goes to production
